.github/workflows/build.yml, .projenrc.js, scripts/lambda-test-update.sh, scripts/lambda-test.sh
This PR includes changes that improves the ci/cd pipeline:
- go tests
- dependencies for all jobs
=> feat(CI): Improve github actions

.github/workflows/build.yml, .github/workflows/release.yml, .projenrc.js, lambda/__snapshots__/main_test.snap
This PR introduces go tests in PRs
=> feat(CI): tests for go

README.md
=> fix(Docs): Minor changes to readme

renovate.json
=> chore(CI): renovate bundle go deps

README.md
I added some documentation about advanced configuration
=> chore(docs): advanced configuration

.github/workflows/build.yml, .github/workflows/release.yml, .mergify.yml, .projen/tasks.json, .projenrc.js, README.md, package.json, renovate.json
=> feat: add python packages

README.md
=> chore: change image link to gh.com for pypi

README.md
=> chore: add download counter badges

src/index.ts, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json
=> fix: Increase timeout for provider from default 3 to 60 seconds

README.md
=> feat: start FAQ and describe issues that already occured

test/secret.test.ts
=> chore: Testcoverage

.npmignore, .projenrc.js
=> chore: better npm ignore

.github/workflows/auto-approve.yml, .github/workflows/build.yml, .github/workflows/pull-request-lint.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .projen/tasks.json, package.json, yarn.lock
=> fix: manual upgrade

README.md
Prepare release of version 1.0.0
=> chore: prepare release of version 1.0.0

README.md
=> chore: minor readme fix

.projenrc.js, README.md, package.json, yarn.lock
=> feat: minor fixes

src/index.ts
=> fix: handle imported kms Keys for Secret

src/index.ts, test/secret.test.ts, yarn.lock
=> chore: Tests for last fix

lambda/main.go, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json
=> fix: error output if putSecretValue fails

.projenrc.js, README.md, package.json
=> feat: move cdk-sops-secrets to dbs organization

.github/workflows/build.yml, .github/workflows/release.yml, .projenrc.js, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json, test/secret-multikms.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-multikms.integ.snapshot/SecretIntegrationInline.template.json
Fixes warnings in build pipeline:
- update more workflow actions
=> fix: update github actions

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .projen/tasks.json, .projenrc.js, API.md, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-multikms.integ.snapshot/SecretMultiKms.assets.json, test/secret-multikms.integ.snapshot/SecretMultiKms.template.json
=> fix: build pipeline

.github/workflows/release.yml, .projenrc.js
=> fix: pipeline go - nuget

.projenrc.js, package.json
=> fix: package is stable

lambda/__snapshots__/handler_env_test.snap, lambda/events/event_create_s3_env_as_json_simple.json, lambda/events/event_create_s3_env_simple.json, lambda/main.go, src/index.ts
=> fix: dotenv

src/index.ts, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-multikms.integ.snapshot/SecretMultiKms.assets.json, test/secret-multikms.integ.snapshot/SecretMultiKms.template.json
=> fix: no fallthrough

CONTRIBUTING.md, lambda/main.go, scripts/lambda-build.sh
=> fix: contribution guide, error messages and sha1sum

README.md
=> chore: document how to disable iam generation

CONTRIBUTING.md, README.md, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-multikms.integ.snapshot/SecretMultiKms.assets.json, test/secret-multikms.integ.snapshot/SecretMultiKms.template.json
=> chore: docs typo

API.md, src/SopsSync.ts, test/secret-asset.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-asset.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-asset.integ.ts, test/secret-inline.integ.snapshot/SecretIntegrationInline.assets.json, test/secret-inline.integ.snapshot/SecretIntegrationInline.template.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.assets.json, test/secret-manual.integ.snapshot/SecretIntegrationAsset.template.json, test/secret-multikms.integ.snapshot/SecretMultiKms.assets.json, test/secret-multikms.integ.snapshot/SecretMultiKms.template.json
=> fix: kms key asset permissions

lambda/internal/sops/__snapshots__/sopsfile-complex.enc-age.json.snap, lambda/internal/sops/sops.go, test-secrets/json/sopsfile-complex.enc-age.json, test-secrets/json/sopsfile-complex.json
=> fix: html encoding
